package org.onliner.spring.c51.entity.phone.mobile.enums;

public enum Color {

    AIR_FORCE_BLUE("военно воздушный голубой"),
    ALICE_BLUE("голубой Алисы Рузвельт"),
    ALIZARIN_CRIMSON("ализариновый кармазин"),
    ALMOND("миндальный"),
    AMARANTH("амарант"),
    AMARANTH_PINK("амарантовый розовый"),
    AMBER("янтарный"),
    AMERICAN_ROSE("американский розовый"),
    AMETHYST("аметистовый"),
    ANTI_FLASH_WHITE("белый защитный от вспышки"),
    APPLE_GREEN("яблочный зеленый"),
    APRICOT("абрикосовый"),
    AQUA("аква (циан)"),
    AQUAMARINE("аквамарин (морская волна)"),
    ARMY_GREEN("армейский зеленый"),
    ARSENIC("мышьяк"),
    ARYLIDE_YELLOW("желтый арилид (моноазо)"),
    ASH_GRAY("пепельно серый"),
    ASPARAGUS("спаржа"),
    ATOMIC_TANGERINE("атомный мандариновый"),
    AUBURN("красновато каштановый"),
    AUREOLIN("желтый кобальт / ауреолин"),
    AZURE("лазурный, небесный"),
    BABY_BLUE("младенческий синий"),
    BANANA_YELLOW("банановый желтый"),
    BATTLESHIP_GRAY("военно морской серый"),
    BEIGE("бежевый"),
    BISTRE("бистер (буковая сажа)"),
    BITTERSWEET("сладко горький паслён"),
    BLACK("черный"),
    BLOND("блондин(ка)"),
    BLUE("синий"),
    BOLE("ствол дерева"),
    BONDI_BLUE("вода пляжа Бондай"),
    BONE("костяной"),
    BRIGHT_GREEN("ярко зеленый"),
    BRITISH_RACING_GREEN("британский гоночный зеленый"),
    BRONZE("бронза"),
    BROWN("коричневый"),
    BUFF("буйволиная кожа"),
    BURGUNDY("бургундское вино"),
    BURNT_ORANGE("жженый оранжевый"),
    BURNT_SIENNA("жжёная сиена"),
    BURNT_UMBER("жжёная умбра"),
    BYZANTIUM("византийский"),
    CADET_GRAY("кадетский серый"),
    CAMBRIDGE_BLUE("кембриджский голубой"),
    CAMEL("верблюд"),
    CAMOUFLAGE_GREEN("камуфляжный зеленый"),
    CANDY_APPLE_RED("красный   яблоко в карамели"),
    CARDINAL("кардинал"),
    CARMINE("карминный"),
    CARMINE_PINK("карминно розовый"),
    CARNATION_PINK("розовая гвоздика"),
    CARNELIAN("сердоликовый"),
    CAROLINA_BLUE("голубой унив.Сев.Каролины"),
    CARROT_ORANGE("морковно оранжевый"),
    CELADON("селадон"),
    CERISE("светло вишнёвый"),
    CERISE_PINK("вишнево розовый"),
    CERULEAN("небесный"),
    CHAMOISEE("цвет альпийской козы"),
    CHAMPAGNE("шампанское (бледно палевый)"),
    CHARCOAL("древесный уголь"),
    CHARTREUSE("шартрез"),
    CHARTREUSE_YELLOW("желтый шартрез"),
    CHERRY_BLOSSOM_PINK("розовые цветы вишни"),
    CHESTNUT("каштановый"),
    CHOCOLATE("шоколадный"),
    CHROME_YELLOW("хромовый желтый"),
    CIEL("тускло голубой"),
    CINEREOUS("пепельно коричневатый"),
    CITRINE("цитрин, лимонный"),
    CLOVER("клевер"),
    COBALT_BLUE("кобальтовый синий"),
    COFFEE("кофейный"),
    COOL_GRAY("холодный серый"),
    COPPER("медный"),
    COQUELICOT("дикий мак"),
    CORAL("коралловый"),
    CORAL_PINK("кораллово розовый"),
    CORAL_RED("кораллово красный"),
    CORDOVAN("кордовская дубленая кожа"),
    CORNFLOWER_BLUE("васильковый"),
    CORNSILK("кукурузные рыльца"),
    COSMIC_LATTE("космический латте"),
    CREAM("сливочный"),
    CRIMSON("кармазин"),
    CYAN("голубой, циан"),
    DARK_BLUE("темно синий"),
    DARK_GOLDENROD("темный золотарник"),
    DARK_OLIVE_GREEN("темный оливково зеленый"),
    DARK_PINK("темно розовый"),
    DARK_PURPLE("темно фиолетовый"),
    DARK_RED("темно красный"),
    DARK_SALMON("темно лососевый"),
    DARK_SPRING_GREEN("темный весенний зеленый"),
    DARK_TIMBERWOLF("темный лесной волк"),
    DARTMOUTH_GREEN("дартмутский зеленый"),
    DAVY_S_GRAY("серый Дэви"),
    DEEP_CARMINE_PINK("темный карминно розовый"),
    DEEP_CARROT_ORANGE("насыщенный морковнооранжевый"),
    DEEP_PINK("насыщенный розовый"),
    DEEP_SKY_BLUE("насыщенный голубой"),
    DENIM("джинсовый"),
    DESERT_SAND("песок пустыни"),
    EARTH_YELLOW("земляной желтый"),
    ECE_SAE_AMBER("янтарный ECE/SAE"),
    ECRU("небелёный лён (экрю)"),
    EGGPLANT("баклажановый"),
    EGGSHELL("скорлупа"),
    EGYPTIAN_BLUE("египетская синь"),
    ELECTRIC_BLUE("электрический голубой"),
    ELECTRIC_CRIMSON("электрический кармазин"),
    ELECTRIC_GREEN("электрический зеленый"),
    EMERALD("изумрудный"),
    ETON_BLUE("итонский голубой"),
    FALLOW("пашня под паром"),
    FALU_RED("цвет шведских домов"),
    FANDANGO("фанданго"),
    FAWN("оленёнок"),
    FELDGRAU("немецкий защитный"),
    FERN_GREEN("папортниковый зеленый"),
    FIELD_DRAB("полевой защитный (воен.)"),
    FIRE_BRICK("огнеупорный кирпич"),
    FIRE_ENGINE_RED("красный для пожарных машин"),
    FLAME("огненный"),
    FLAVESCENT("желтоватый"),
    FLAX("льняной"),
    FOLLY("безумие"),
    FOREST_GREEN("лесной зеленый"),
    FUCHSIA("фуксия"),
    FULVOUS("(рыжевато бурый)"),
    GAMBOGE("гуммигут"),
    GARNET("гранат"),
    GHOST_WHITE("призрачный белый"),
    GLAUCOUS("(сизый, сероватый)"),
    GOLD("золотой"),
    GOLD_METALLIC("золотой (металлический)"),
    GOLDEN_POPPY("калифорнийский мак"),
    GOLDEN_YELLOW("золотисто желтый"),
    GOLDENROD("золотарник"),
    GRAY_ASPARAGUS("серо спаржевый"),
    GRAY("серый"),
    GREEN_YELLOW("желто зеленый"),
    GREEN("зеленый"),
    HAN_BLUE("ханьский синий"),
    HAN_PURPLE("ханьский фиолетовый"),
    HANSA_YELLOW("желтый ганза"),
    HARLEQUIN("арлекин"),
    HELIOTROPE("гелиотроп"),
    HOLLYWOOD_CERISE("голливудский вишневый"),
    HONEYDEW("мякоть мускатной дыни"),
    HOT_MAGENTA("ярко пурпурный"),
    HOT_PINK("ярко розовый"),
    HUNTER_GREEN("охотничьий зеленый"),
    ICTERINE("желтый (о птицах)"),
    INDIGO("индиго"),
    INTERNATIONAL_ORANGE("международный оранжевый"),
    IRIS("ирис"),
    ISABELLINE("Изабелла"),
    IVORY("слоновая кость"),
    JADE("нефрит"),
    JASMINE("жасминовый"),
    JONQUIL("жонкиль (нарцисс)"),
    JUNGLE_GREEN("зеленые джунгли"),
    KELLY_GREEN("Келли (ирландский)"),
    KHAKI("хаки"),
    LAVA("лава"),
    LAVENDER("лавандовый"),
    LAVENDER_BLUSH("лавандово розовый"),
    LAVENDER_MIST("лавандовая дымка"),
    LAVENDER_PINK("лавандово розовый"),
    LAWN_GREEN("газон, лужайка"),
    LEMON("лимонный"),
    LEMON_CHIFFON("лимонный торт суфле"),
    LIGHT_BLUE("голубой"),
    LIGHT_PINK("светло розовый"),
    LILAC("сиреневый (лиловый)"),
    LIME("лайм (желто зелёный)"),
    LIME_GREEN("лаймово зеленый"),
    LINEN("холст, парусина, лён"),
    LIVER("печёночный"),
    LUST("вожделение"),
    MAGENTA("пурпурный (полиграфич. sRGB)"),
    MAGIC_MINT("волшебный мятный"),
    MAGNOLIA("магнолия"),
    MAHOGANY("красное дерево"),
    MAIZE_BE_CORN_AE("кукурузный"),
    MALACHITE("малахит"),
    MAROON("каштановый (от франц.)"),
    MAUVE("цвет мов"),
    MEDIUM_TAUPE("средний кротовый"),
    MIDNIGHT_BLUE("полночный синий"),
    MIDNIGHT_GREEN("полночный зеленый"),
    MIKADO_YELLOW("желтый микадо"),
    MINT("мятный"),
    MINT_CREAM("мятная конфетка"),
    MOSS_GREEN("моховой (вариант)"),
    MOUNTBATTEN_PINK("розовый Маунтбеттена"),
    MUSTARD("горчичный"),
    MYRTLE("мирт"),
    NAPLES_YELLOW("неаполитанский желтый"),
    NAVAJO_WHITE("светлый Навахо"),
    NAVY_BLUE("военно морской темно синий"),
    NEON_GREEN("зеленый неон"),
    OCHRE("охра"),
    OLD_GOLD("старое золото"),
    OLD_LACE("старое кружево"),
    OLIVE("оливковый"),
    OLIVE_DRAB_3("оливковый камуфляжный 3"),
    OLIVE_DRAB_7("оливковый камуфляжный 7"),
    OLIVINE("оливин (хризолит)"),
    ORANGE_RED("оранжево красный"),
    ORANGE("оранжевый"),
    ORANGE_WEB("оранжевый (веб)"),
    ORANGE_PEEL("кожура апельсина"),
    ORANGE_TEA_ROSE("оранжевая чайная роза"),
    ORCHID("орхидея"),
    PALE_GOLD("бледно золотой"),
    PALE_GOLDENROD("бледный золотарник"),
    PALE_GREEN("бледно зеленый"),
    PALE_TAUPE("бледный кротовый"),
    PAPAYA_WHIP("взбитые сливки с папайей"),
    PARIS_GREEN("парижская/швейнфуртская зелень"),
    PAYNE_S_GRAY("серый Пейна"),
    PEACH_ORANGE("персиково оранжевый"),
    PEACH_YELLOW("персиково желтый"),
    PEACH("персиковый"),
    PEAR("груша"),
    PEARL("жемчужный"),
    PERIWINKLE("цвет перванш (барвинок)"),
    PERSIAN_BLUE("персидский синий"),
    PERSIAN_GREEN("персидский зеленый"),
    PERSIAN_ORANGE("персидский оранжевый"),
    PERSIAN_PINK("персидский розовый (pink)"),
    PERSIAN_RED("персидский красный"),
    PERSIAN_ROSE("персидский розовый (rose)"),
    PERSIMMON("хурма"),
    PHTHALO_BLUE("фталоцианин"),
    PHTHALO_GREEN("зеленый фталоцианин"),
    PINE_GREEN("зеленая сосна"),
    PINK_ORANGE("розово оранжевый"),
    PINK("розовый"),
    PISTACHIO("фисташковый"),
    PLATINUM("платиновый"),
    PLUM("сливовый"),
    PORTLAND_ORANGE("портлендский оранжевый"),
    POWDER_BLUE("(зеленовато голубой)"),
    PRINCETON_ORANGE("принстонский оранжевый"),
    PRUSSIAN_BLUE("берлинская лазурь"),
    PUCE("цвет пюс"),
    PUMPKIN("тыква"),
    PURPLE("фиолетовый"),
    PURPLE_TAUPE("фиолетовый кротовый"),
    RASPBERRY("малиновый"),
    RASPBERRY_ROSE("малиново розовый"),
    RAW_UMBER("натуральная умбра"),
    RED_VIOLET("красно фиолетовый"),
    RED("красный"),
    REDWOOD("секвойя"),
    RIFLE_GREEN("зеленый стрелков"),
    ROBIN_EGG_BLUE("яйцо странствующего дрозда"),
    ROSE("розовый"),
    ROSE_MADDER("крапп марена"),
    ROSE_PINK("розово розовый :)"),
    ROSE_QUARTZ("розовый кварц"),
    ROSE_TEA_ROSE("розовая чайная роза"),
    ROSEWOOD("темное тропическое дерево"),
    ROSSO_CORSA("красный для автогонок"),
    ROYAL_BLUE_TRADITIONAL("королевский синий (традиц.)"),
    ROYAL_BLUE_WEB("королевский синий (веб)"),
    RUBY("рубиновый"),
    RUFOUS("(красновато коричневый)"),
    RUSSET("(красновато коричневый)"),
    RUST("цвет ржавчины"),
    SAFETY_ORANGE("спасательный оранжевый"),
    SAFFRON("шафранный"),
    SALMON("лососевый"),
    SALMON_PINK("лососево розовый"),
    SANDY_BROWN("песочно коричневый"),
    SANGRIA("сангрия"),
    SAP_GREEN("зеленый из ягод крушины"),
    SAPPHIRE("сапфировый"),
    SCARLET("алый"),
    SCHOOL_BUS_YELLOW("школьный автобус"),
    SEA_GREEN("морской зеленый"),
    SEAL_BROWN("морской котик"),
    SEASHELL("ракушка"),
    SELECTIVE_YELLOW("селективный желтый"),
    SEPIA("сепия"),
    SIENNA("сиена"),
    SILVER("серебряный"),
    SINOPIA("синопия"),
    SKOBELOFF("Скобелев"),
    SKY_BLUE("голубой"),
    SLATE_GRAY("серый аспидный сланец"),
    SPRING_BUD("весенние почки"),
    SPRING_GREEN("весенний зеленый"),
    STEEL_BLUE("стальной синий"),
    SUNGLOW("солнечный"),
    SUNSET("закат"),
    TAN("дубильная кора"),
    TANGELO("фрукт танжело"),
    TANGERINE("мандарин"),
    TANGERINE_YELLOW("мандариново желтый"),
    TAUPE("крот (лат.)"),
    TAUPE_GRAY("серый кротовый"),
    TAWNY("дублёная кожа"),
    TEA_GREEN("зеленый чай"),
    TEAL("(синевато зеленый) утиный"),
    TENN_U00E9("геральдический бурооранжевый"),
    TERRACOTTA("терракота"),
    THISTLE("цветок чертополоха"),
    TIMBERWOLF("лесной волк"),
    TITANIUM_YELLOW("титановый желтый"),
    TOMATO("помидор"),
    TURQUOISE("бирюзовый"),
    TUSCAN_RED("тосканский красный"),
    TYRIAN_PURPLE("пурпурный, порфир"),
    ULTRAMARINE("ультрамарин"),
    UMBER("умбра"),
    UPSDELL_RED("памяти Reverend G Upsdell"),
    UROBILIN("уробилин"),
    VANILLA("ванильный"),
    VENETIAN_RED("венецианский красный"),
    VERDIGRIS("ярь медянка (зеленая патина)"),
    VERMILION("киноварь"),
    VIOLET("фиолетовый"),
    VIRIDIAN("виридиан (окись хрома III)"),
    WENGE("венге"),
    WHEAT("пшеничный"),
    WHITE("белый"),
    WINE("винный"),
    WISTERIA("глициния"),
    XANADU("Шанду"),
    YALE_BLUE("йельский синий"),
    YELLOW("желтый");



    private final String displayValue;

    private Color(String displayValue) {
        this.displayValue = displayValue;
    }

    public String getDisplayValue() {
        return displayValue;
    }

}
